### ISSUE TITLE
Cannot `npm link` the repo

### ISSUE THREAD

**Issue by WesleyGoncalves** [docsifyjs/docsify-cli#103]
When I run `npm link` (after running `npm install`), I get this error

```sh
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules\docsify-cli\bin\docsify
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\user\AppData\Roaming\npm\node_modules\docsify-cli\bin\docsify'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-04-26T00_15_38_339Z-debug.log
```

Packages versions:

- docsify-cli v4.4.0 
- Windows 10
- node 12.14.1
- npm 6.13.4

Apparently it cannot find the bin file. 
Does anyone know why?

**Comment by WesleyGoncalves** [comment]
Apparently, as [@3329 answers in this post](https://stackoverflow.com/a/24093486/8522818),  the package.json file `bin` key must contain a relative path to the binary file and this file is in `lib/cli.js`. 

So, package.json file should contain:

```js
  "bin": {
    "docsify": "lib/cli.js"
  },
```

It should now be possible to successfully run `npm link`. 

---

However, when you run `docsify` command in terminal, this error occurs ` C:\Users\user\AppData\Roaming\npm/node_modules/docsify-cli/lib/cli.js: line 1: syntax error near unexpected token `('`.

To fix it, the `lib/cli.js` file should begin with `#!/usr/bin/env node` as suggested by the [same answer mentioned above](https://stackoverflow.com/a/24093486/8522818).

Does anyone have anything to comment about this? 
`npm install -g docsify-cli`  works, but `npm link` doesn't.

**Comment by sy-records** [comment]
You need to run `npm run prebuild` first.
