### ISSUE TITLE
Can you please release a new version with the security update to update-notifier?

### ISSUE THREAD

**Issue by julienw** [docsifyjs/docsify-cli#121]
Hi,
I noticed that you bumped the version for update-notifier recently (#112 #114). Would you please be kind enough to release a new version with this change, so that downstream projects can get the fix? Thanks a ton!

**Comment by anikethsaha** [comment]
We will release it soon.

**Comment by sy-records** [comment]
🎉 [v4.4.2](https://github.com/docsifyjs/docsify-cli/releases/tag/v4.4.2) released!
