### ISSUE TITLE
when i install docsify-cli, it's blocked

### ISSUE THREAD

**Issue by sukai-cheng** [docsifyjs/docsify-cli#122]
it just blocked
npm i docsify-cli -g
⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ rollbackFailedOptional: verb npm-session c62e485c680d3599

**Comment by anikethsaha** [comment]
Probably some network issue or issue with npm. 

still, Please give some more info, error message, stack trace, your environment, package version, node version.

**Comment by sukai-cheng** [comment]
I have solved it, I changed the source of npm

Anix <notifications@github.com> 于2020年9月29日周二 下午11:37写道：

**Comment by anikethsaha** [comment]
Good to know
