### ISSUE TITLE
Request for generate function into a new release

### ISSUE THREAD

**Issue by jochne** [docsifyjs/docsify-cli#131]
Hi,
I notice that generate command is published into master, but cannot pull it into my local version, could you please make it a new release to make the generate command accessible?

**Comment by sy-records** [comment]
We will release a new version as soon as possible.

You can also manually build locally at

```shell
git clone git@github.com:docsifyjs/docsify-cli.git
npm i
npm run build
npm link
```

**Comment by jochne** [comment]
> We will release a new version as soon as possible.
> 
> You can also manually build locally at
> 
> ```shell
> git clone git@github.com:docsifyjs/docsify-cli.git
> npm i
> npm run build
> npm link
> ```

thanks a lot
