### ISSUE TITLE
Does not support routerMode: 'history'

### ISSUE THREAD

**Issue by utybo** [docsifyjs/docsify-cli#132]
When using `docsify serve` when routerMode is enabled, navigating directly to /Something does not work and instead throws a 404 error

Is there any way to work around this?

It would also be nice to have a way to "whitelist" some paths, e.g. so that /Hi *actually* refers to some Hi.html

**Comment by sy-records** [comment]
see https://github.com/docsifyjs/docsify/issues/720

**Comment by utybo** [comment]
The issue you linked is about hosting, my issue is about the dev side of things. I use `docsify serve` to serve my docs *locally* when I'm writing them, and that doesn't support the history router mode.

Is there any way to work around this?

**Comment by sy-records** [comment]
You should see https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

**Comment by sy-records** [comment]
Fixed by #166

**Comment by hxsf** [comment]
@sy-records 
so we need a new release to make it can be used as `npx docsify-cli`.
BTW, docsify-cli@next is alias to 4.0.2, maybe we can make a github action to auto build master branch to npm next label.

**Comment by ASaiAnudeep** [comment]
@sy-records when is this feature going to be released? I see last publish was a [year ago](https://www.npmjs.com/package/docsify-cli).

**Comment by sy-records** [comment]
I will release as soon as possible

**Comment by hxsf** [comment]
A github action to publish a `next` label to npm may be a good solution.
stable release will be marked by version.
a dev release or nightly build will be marked by `next or nightly `.

it's easy to publish a next or nightly package, not worry about bug or break change, and people who want to use it will feedback the break change or bug.



***@***.***
 
From: 沈唁
Date: 2022-03-12 13:51
To: docsifyjs/docsify-cli
CC: 呼啸随风; Comment
Subject: Re: [docsifyjs/docsify-cli] Does not support routerMode: 'history' (#132)
I will release as soon as possible
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sy-records** [comment]
https://github.com/docsifyjs/docsify-cli/releases/tag/v4.4.4 done.
