### ISSUE TITLE
High and moderate vulnerabilities 

### ISSUE THREAD

**Issue by joemc11** [docsifyjs/docsify-cli#134]
1. Install docsify-cli
2. Run yarn audit
3. High and moderate vulnerabilities detected
<img width="697" alt="Screenshot 2021-03-02 at 23 30 27" src="https://user-images.githubusercontent.com/14826627/109729135-56c24e80-7baf-11eb-9ff2-259d073dd587.png">

**Comment by sy-records** [comment]
Thank you for your feedback, the docsify dependency issue has been fixed, but there is no release version yet, we will release it as soon as possible.

**Comment by sy-records** [comment]
[v4.4.3](https://github.com/docsifyjs/docsify-cli/releases/tag/v4.4.3) released
