### ISSUE TITLE
"docsify g ./docs"(auto generate sidebar ) generate unexpected results

### ISSUE THREAD

**Issue by he0xwhale** [docsifyjs/docsify-cli#139]
1. My directory structure is below:

    ![选区_008](https://user-images.githubusercontent.com/80368859/112238510-c04dee00-8c7f-11eb-8357-83356d7da4ce.png)
2. after executing the command `docsify g ./docs`,I got the file `_sidebar.md` as below:

> - [README](README.md)
> - [README](README.md)
> 
> - contents
>   - [dev1](contents/dev/dev1.md)
>   - [dev2](contents/dev/dev2.md)
>   - [dev3](contents/dev/dev3.md)
>   - [sec1](contents/sec/sec1.md)
>   - [tech1](contents/tech/tech1.md)
3. there are two problems:
    1. there is only one README.md,but two README.md items are written .
    2. i want the contents of the README.md like below:
        > - [README](README.md)
        > 
        > - contents
        >   
        >   - dev
        >     
        >     - [dev1](contents/dev/dev1.md)
        >     - [dev2](contents/dev/dev2.md)
        >   - [dev3](contents/dev/dev3.md)
        >   - [sec1](contents/sec/sec1.md)
        >   - [tech1](contents/tech/tech1.md)

        I think this will be more appropriate.

**Comment by sy-records** [comment]
1. My test does not generate two README
2. You can use `docsify g ./docs/contents/`, Then modify it
