### ISSUE TITLE
Failed at the docsify@4.12.1 postinstall script.

### ISSUE THREAD

**Issue by southfly** [docsifyjs/docsify-cli#150]
[root@mail Temp]# npm install -g opencollective-postinstall
/home/south/Applications/Node/node-v10.24.1-linux-x64/bin/opencollective-postinstall -> /home/south/Applications/Node/node-v10.24.1-linux-x64/lib/node_modules/opencollective-postinstall/index.js
+ opencollective-postinstall@2.0.3
updated 1 package in 0.253s
[root@mail Temp]# npm install docsify-cli -g
/home/south/Applications/Node/node-v10.24.1-linux-x64/bin/docsify -> /home/south/Applications/Node/node-v10.24.1-linux-x64/lib/node_modules/docsify-cli/bin/docsify

> docsify@4.12.1 postinstall /home/south/Applications/Node/node-v10.24.1-linux-x64/lib/node_modules/docsify-cli/node_modules/docsify
> opencollective-postinstall

sh: opencollective-postinstall: command not found
npm WARN ws@7.5.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.5.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/docsify-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! syscall `spawn`
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! docsify@4.12.1 postinstall: `opencollective-postinstall`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the docsify@4.12.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-03T08_31_11_358Z-debug.log

**Comment by southfly** [comment]
[2021-08-03T08_31_11_358Z-debug.log.txt](https://github.com/docsifyjs/docsify-cli/files/6922600/2021-08-03T08_31_11_358Z-debug.log.txt)

**Comment by sy-records** [comment]
You need to softlink `/home/south/Applications/Node/node-v10.24.1-linux-x64/bin/opencollective-postinstall` to `/usr/local/bin/ `

**Comment by southfly** [comment]
[root@centos south]# ln -s /home/south/Applications/Node/node-v10.24.1-linux-x64/bin/opencollective-postinstall /usr/bin/
ln: failed to create symbolic link ‘/usr/bin/opencollective-postinstall’: File exists
[root@centos south]# sh opencollective-postinstall
/usr/local/bin/opencollective-postinstall: opencollective-postinstall: line 3: syntax error near unexpected token `value'
/usr/local/bin/opencollective-postinstall: opencollective-postinstall: line 3: `function isTrue(value) {'
[root@centos south]# npm i docsify-cli -g
/home/south/Applications/Node/node-v10.24.1-linux-x64/bin/docsify -> /home/south/Applications/Node/node-v10.24.1-linux-x64/lib/node_modules/docsify-cli/bin/docsify

> docsify@4.12.1 postinstall /home/south/Applications/Node/node-v10.24.1-linux-x64/lib/node_modules/docsify-cli/node_modules/docsify
> opencollective-postinstall

sh: opencollective-postinstall: command not found
npm WARN ws@7.5.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.5.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/docsify-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! docsify@4.12.1 postinstall: `opencollective-postinstall`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the docsify@4.12.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-03T13_14_15_121Z-debug.log

**Comment by southfly** [comment]
[2021-08-03T13_14_15_121Z-debug.log.txt](https://github.com/docsifyjs/docsify-cli/files/6924318/2021-08-03T13_14_15_121Z-debug.log.txt)

**Comment by southfly** [comment]
[root@centos _logs]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
[root@centos _logs]# node -v
v10.24.1
[root@centos _logs]# npm -v
6.14.12
