### ISSUE TITLE
Yargs causing npm audit warnings

### ISSUE THREAD

**Issue by taylortom** [docsifyjs/docsify-cli#157]
Summary from npm:
| Moderate | Inefficient Regular Expression Complexity in chalk/ansi-regex |
| - | - |
| Package | ansi-regex |
| Patched in | >=5.0.1 |
| More info | https://github.com/advisories/GHSA-93q8-gq69-wqmw |

Issue looks to be fixed in yargs 15+ (guessing 16+ will be a no-go for you guys atm as it drops node v10 support).

**Comment by taylortom** [comment]
Just spotted this https://github.com/docsifyjs/docsify-cli/pull/153

**Comment by sy-records** [comment]
Thanks for your feedback, I will merge them.
