### ISSUE TITLE
Option to regenerate the README.md file

### ISSUE THREAD

**Issue by bennycode** [docsifyjs/docsify-cli#167]
The command `docsify init ./docs` creates the following files: `.nojekyll`, `index.html` & `README.md`. Is there the possibility to selectively recreate files? I just want the `README.md` to be regenerated but not the rest.

**Comment by sy-records** [comment]
Thank you for your advice.
However, this command is usually run only once to initialize the project, after that it is all on its own to modify the content, so it doesn't make sense to add regenerate.
