### ISSUE TITLE
Vulnerable version because of outdated marked version as transitive dependency

### ISSUE THREAD

**Issue by bennycode** [docsifyjs/docsify-cli#168]
I like docsify but I just got an alert from Dependabot about a security vulnerability from it:

> docsify-cli@4.4.3 requires marked@^1.2.9 via a transitive dependency on docsify@4.12.2

Marked in docsify has to be updated to v4.0.10 to fix its denial of service vulnerability.

**Comment by sy-records** [comment]
Thank you for your feedback, but for some reason the upgrade is temporarily unavailable.
see https://github.com/docsifyjs/docsify/pull/1503
