### ISSUE TITLE
Support change the default binding of Docsify from localhost to 0.0.0.0

### ISSUE THREAD

**Issue by Dragonchu** [docsifyjs/docsify-cli#208]
I deploy my service using Docker, but I'm using a platform where I can't specify the Docker run command myself. In this case, Docsify starts by default using localhost, which causes my service to be inaccessible. I hope to be able to specify localhost as 0.0.0.0.

**Comment by sy-records** [comment]
If you are using it at deployment time, it is recommended to use another web server such as nginx etc.

**Comment by sy-records** [comment]
The serve command `docsify serve docs`  listens on all, so you can use ip to access.

```bash
tcp46      0      0  *.3000                 *.*                    LISTEN
```
