### ISSUE TITLE
本地初始化加载插件

### ISSUE THREAD

**Issue by LancelotLewis** [docsifyjs/docsify-cli#3]
使用`-l`本地化初始化时，没有配置可以默认加载三方插件，需要从git仓库找到插件的源码，较为麻烦

**Comment by baihe** [comment]
Maybe we need a template mechanism.
What we did now is adding an expanded yarg,  like -f $template, it will read the corresponding file instead. If set local flag, it will fetch those resources from unpkg.
This function is useful for teams that want to build things upon docsify.

Thanks
