### ISSUE TITLE
Unexpected autoscroll

### ISSUE THREAD

**Issue by bashkirtsevich** [docsifyjs/docsify-cli#42]
Greetings.

We have unexpected behaviour of docsify, when we scroll long page to bottom and open relative link (looks like `https://docsify.company.com/documentation/#/folder1/README.md`), or absolute link in `docsify`, on the dest page, page autoscroll in bottom, or half of page. Is possible to prevent autoscrolling in relative paths?

**Comment by sokovnich** [comment]
I have the same problem.
