### ISSUE TITLE
docsify serve 命令支持后台运行程序么？

### ISSUE THREAD

**Issue by yl-yue** [docsifyjs/docsify-cli#57]
如： `docsify serve . -d`

**Comment by yl-yue** [comment]
nohup docsify serve docs > nohup.out 2>&1 &

**Comment by cleexiang** [comment]
@yl-yue 我试了下不行呢

**Comment by yl-yue** [comment]
> @yl-yue 我试了下不行呢

看上面我的问题与回答，这个命令是没毛病的，这样做可以后台运行所有程序，我是centos7
