### ISSUE TITLE
Someone please help me run Docsify on windows, I'm confused.

### ISSUE THREAD

**Issue by silvererudite** [docsifyjs/docsify-cli#64]
I have installed Docsify using npm then I see there are 3 folders, namely docsify, docsify-cli, docsify-server-renderer. Now what do I do next? i tried to create a folder and initialize it using command line but it says docsify is not recognized as internal/ external command even though I installed it. The getting started page on the Docsify site is confusing to me. It would be a great if someone would just tell me initial steps on how to get started on Windows environment.

**Comment by anikethsaha** [comment]
what was your installlation scope ?

you need to install it globally 

Check the docs https://docsify.js.org/#/quickstart

**Comment by Zurdge** [comment]
@anikethsaha 
I'm experiencing the same install issue.
node version - v10.16.0
npm version - 6.12.1
(Not sure if the version matters)

step 1 - 'npm i docsify-cli -g'
step 2 - 'docsify init ./docs'

result - 
''docsify' is not recognized as an internal or external command,
operable program or batch file.'

I'm following the steps seen on there.
https://docsify.js.org/#/quickstart

**Comment by anikethsaha** [comment]
Can you share the versions for docsify-cli and your os!

**Comment by Zurdge** [comment]
docsify-cli version is unknown because it can't be installed.
OS is windows 10

**Comment by anikethsaha** [comment]
> docsify-cli version is unknown because it can't be installed.

npm list  -g --depth=0

Also,
try installing it again and check. Better uninstall the global Cli and do it .

**Comment by Zurdge** [comment]
Re-installed Node and now everything works as it should.

**Comment by AnujaChangede** [comment]
We are facing a slightly different issue. First we got the docsify not recognized error. So we opened the command prompt in Admin mode and the error went away. The site built successfully and we got a message that its up on http://localhost:5000.
However, when I run the localhost:5000, it doesn't show the default text from Readme.md file. The site appears blank.
Can someone please help?
Thanks in Advance!

**Comment by Uggeli** [comment]
'npx docsify init ./docs' did work for me

**Comment by elgransan** [comment]
I have to use 'npx docsify-cli init ./docs'  and then 'npx docsify-cli serve ./docs'

**Comment by Aahil13** [comment]
Thank you @elgransan! It works perfectly for me
