### ISSUE TITLE
Bug: /usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by BioniCosmos** [docsifyjs/docsify-cli#78]
After the installation, I try to run docsify. However, there's an error saying `/usr/bin/env: ‘node\r’: No such file or directory`.
Finally, I found the solution to the problem.
Just to use `dos2unix` to convert `/use/local/lib/node_modules/docsify-cli/bin/docsify` to Unix format.
Maybe it is the format(dos) of the file that cause the problem.

**Comment by DeeperDing** [comment]
Please fix it!

**Comment by nsainaney** [comment]
I'm experiencing this issue as well. It's because the file:

`node_modules/docsify-cli/bin/docsify` has CRLF line endings instead of LF (\r instead of \n) with are Windows line endings. You can fix this locally by finding the docsify file locally (`which docsify`) and changing the line endings using an editor like vscode or something like dos2unix.

I can't submit a PR because the repo is correct but somehow, the npm package is messed up.

This is what I see for the bin file in vscode. See the highlight in the bottom right:

![image](https://user-images.githubusercontent.com/306293/70379880-aa2fe900-18e7-11ea-90f7-e442347a9743.png)

**Comment by anikethsaha** [comment]
Are you guys on the latest version?
Might be, cause I published from my windows machine but it's weird as I never faced this type of bugs.

@jamesgeorge007 Can you take a look here.

**Comment by nsainaney** [comment]
Yes I'm on 4.4.0. On a Linux/MacOS machine, the following shows that the `bin/docsify` file uses CRLF:

```
npm pack docsify-cli
tar -xf docsify-cli-4.4.0.tgz
code package/bin/docsify
```

The above downloads the docsify-cli tarball from npm and unpacks the contents and finally, opens it in VSCode. The file shows CRLF line endings.

The issue could be because it's published using a Windows machine. Git is probably converting CRLF's to LF's which is why the repo file is fine. It's just the published file in the bin folder.

**Comment by anikethsaha** [comment]
@felangel if it's possible can you do a patch release if you have a `linux/MacOS` system !

**Comment by CN-GuoZiyang** [comment]
You can simply cd to /usr/local/lib/node_modules/docsify-cli/bin
and open docsify with vim
`sudo vim docsify`
then you can fix the line endings of the file with
`:set ff=unix`
then save and quit
`:wq`
and everything should be fine!

**Comment by raulfdm** [comment]
I just opened `node_modules/.bin/docsify`, save the file and It's works again.

But it's indeed annoying.

**Comment by anikethsaha** [comment]
@jamesgeorge007 could you do a patch release soon.

**Comment by raulfdm** [comment]
I was taking a look on the project structure, does it makes sense to have a sort of `index.js` or `main.js` and runs a tool like `rollup` (very basic config)  to avoid this kind of problem?

**Comment by anikethsaha** [comment]
yeah...that's a good option to have proper build steps and automatic releases. 
I would say we can just wait for a while until @jamesgeorge007 finishes his work of adding e2e. Then we can add these build systems.
Feel free to submit an issue and we can discuss that there separately.

**Comment by raulfdm** [comment]
Will do! Thanks @anikethsaha

**Comment by raulfdm** [comment]
This issue will be fixed on next release :)

Thanks @anikethsaha for the feedbacks

**Comment by stevenzeiler** [comment]
> You can simply cd to /usr/local/lib/node_modules/docsify-cli/bin
> and open docsify with vim
> `sudo vim docsify`
> then you can fix the line endings of the file with
> `:set ff=unix`
> then save and quit
> `:wq`
> and everything should be fine!

Ahh it works thank you much.

**Comment by raulfdm** [comment]
@DeeperDing Why is this closed if a there's no new release to fix the issue? 🤔

**Comment by anikethsaha** [comment]
Yup, lets  keep it open until the release

**Comment by nsainaney** [comment]
BTW, if you'd like, you can set up a free CI pipeline with codefresh.io (I'm not affiliated with the firm).

Merges to master can trigger a build and release to npm so build machine issues do not ripple into releases.

I'd be happy to help if required.

________________________________

**Comment by anikethsaha** [comment]
That's really helpful 🎉 
But as of now, you can see that we don't have much of tests in both the repos to get the confidence. So our first priority here is to increase the coverage and test cases.
I am actually thinking of CI piped release but that through GitHub action as this can be more trustful.

**Comment by woss** [comment]
none of the solutions work if you install it via volta

**Comment by mattiasrunge** [comment]
When will a new release with this fix be available?

**Comment by anikethsaha** [comment]
By this month for sure !!!

**Comment by FredericGuilbault** [comment]
Doing 
```
sudo apt install dos2unix
sudo dos2unix /usr/local/lib/node_modules/docsify-cli/bin/docsify
```
Fixe it for me. 
Thx @nsainaney

**Comment by woss** [comment]
yeah, there are also ways to fix it with vim, but we need this cross-platform. :)

**Comment by suazithustra** [comment]
for me, only seems to happen when installed globally with `yarn`

**Comment by hipstersmoothie** [comment]
Adding docsify to a new project and can't get it to work at all 😢

**Comment by anikethsaha** [comment]
> Adding docsify to a new project and can't get it to work at all 😢

@hipstersmoothie  can you describe your issue ? is it related to the CLI ?

also, if CLI is not working propoerly , then adding the docsify 's js and css files from cdn to your html page and create a `div` with `app` class and you have docsify ready to use. Use `window.$docsify` object to configure it !

**Comment by saikrishnadeep** [comment]
This error occurs only when you use `yarn` instead of `npm` to install the package.

**Comment by hipstersmoothie** [comment]
I do use yarn. I downgraded to 4.3.0 to get around the issue

**Comment by saurabhnemade** [comment]
Any eta on this? Looking forward to use it.

**Comment by anikethsaha** [comment]
> Any eta on this? Looking forward to use it.

Cant say!
Feel free to submit the fix !

**Comment by sapkra** [comment]
@anikethsaha I've created a PR which will hopefully fix it.

**Comment by Rabbitzzc** [comment]
if you use `yarn`
cd `~/.config/yarn/global/node_modules/docsify-cli/bin`
and open the code with vscode and delete the last line break
=======================
if you use `nvm & npm `
go to the global node_modules
and open the code with vscode and delete the last line break

**Comment by adrianmcli** [comment]
Strangely enough, the vim method didn't work for me but `dos2unix` did. It's also important to point out that `node_modules/.bin/docsify` is a symlink towards `node_modules/docsify-cli/bin/docsify`.

For best results:

```
brew install dos2unix
sudo dos2unix ./node_modules/docsify-cli/bin/docsify
```

**Comment by transitive-bullshit** [comment]
This has blocked several of my users from contributing to our docs.

As a temporary workaround, I published `docsify-cli-hotfix` which is just a built release of `master` including this fix.

```bash
yarn remove docsify-cli
yarn add --dev docsify-cli-hotfix
```

Then just use the `docsify` command normally.

@maintainers please publish an official patch release for this.

**Comment by anikethsaha** [comment]
it will be done soon. sorry for the delay.
we have an open PR for this and there are few things that need to be fixed before release. 
also, how this is effecting from contributing? if this is about `serve` command, then you can use `live-server` to serve the files/folder as our CLI does that under the hood.

**Comment by jkga** [comment]
If you install it using yarn, the solution of @Rabbitzzc works with additional step
> cd ~/.config/yarn/global/node_modules/docsify-cli/bin

**Updating using vscode**
> code docsify

Then in vscode, make sure that the line-ending is set to `LF`. If not, simply click the `CRLF` and change to `LF`. You can see it on the bottom right of the IDE   

![image](https://user-images.githubusercontent.com/10413754/80100444-90472800-85a2-11ea-9d71-e2a655b5ef1b.png)

**Comment by azl397985856** [comment]
annoying problem

**Comment by xamantra** [comment]
> Doing
> 
> ```
> sudo apt install dos2unix
> sudo dos2unix /usr/local/lib/node_modules/docsify-cli/bin/docsify
> ```
> 
> Fixe it for me.
> Thx @nsainaney

This solution worked for me!
