### ISSUE TITLE
[Proposal] Automate build and releases

### ISSUE THREAD

**Issue by raulfdm** [docsifyjs/docsify-cli#82]
Hello guys.

After the problem reported here (#78), I took a look on the project and I notice the `bin` it's the code you maintain.

Maybe a final solution for this would be automate this process by using a tool like `rollup` with a very basic setup.

What do you think about it?

I have experience with this kind of infrastructure, if you want I can open a PR with a proposal.

**Comment by anikethsaha** [comment]
Great!!
If you are confident with `rollup`, then go for it else I am experienced with webpack so I would lean more towards webpack. But anyway I guess it won't be much of a difference.
Also, don't put everything in one PR, you can do with each step-wise, like first just the setup and then 
changes in the advance level etc....
I guess you can wait until the tests are set up properly it will be easy to pick the breakup if any
 
@jamesgeorge007 what do you think?

**Comment by raulfdm** [comment]
Usually I use `webpack` when I'm working with React, storybook or something which I need to combine HTML + JS.

For pure JS libs I'm seeing a lot of people using rollup because it's WAY simpler. But indeed, It's pretty much the same.

**Comment by raulfdm** [comment]
![automate-build](https://user-images.githubusercontent.com/12464600/71323318-0727c380-24d2-11ea-8389-63b7bab33db4.gif)

**Comment by raulfdm** [comment]
My question is only about how the deployment process will be.

Maybe I can I also came up with an auto-release process via `semantic-release` since you guys are already using conventional commit messages.

**Comment by anikethsaha** [comment]
> Maybe I can I also came up with an auto-release process via semantic-release since you guys are already using conventional commit messages.

yup we are using semantic-release. I guess you added that already in the release.
