### ISSUE TITLE
Fix unix support

### ISSUE THREAD

**Issue by jasonkuhrt** [docsifyjs/docsify-cli#88]
Originally crated issue here https://github.com/docsifyjs/docsify/issues/1001.

```
npm install -g docsify-cli
```
```
❯ docsify --help
env: node\r: No such file or directory
```
```
❯ which docsify
/usr/local/bin/docsify

❯ which node
/Users/jasonkuhrt/.nvm/versions/node/v12.14.1/bin/node

❯ node -v
v12.14.1
```

The issue seems to be an instance of https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

The solution seems to require a change on how this library publishes its source code. Is there a way to make it windows and unix compatible?

**Comment by anikethsaha** [comment]
its a known issue. 
it will be fixed in next release 
https://github.com/docsifyjs/docsify-cli/issues/78
