### ISSUE TITLE
Are there plans to support exporting PDF files?

### ISSUE THREAD

**Issue by jhoneybee** [docsifyjs/docsify-cli#93]
Is it possible to export PDFs so that they can be printed easily

**Comment by anikethsaha** [comment]
PDF of what ? the `.md` files ?

**Comment by anikethsaha** [comment]
May be this will be usefull https://github.com/meff34/docsify-to-pdf-converter

**Comment by jhoneybee** [comment]
thank you very much @anikethsaha
