### ISSUE TITLE
SSR not working

### ISSUE THREAD

**Issue by theBliz** [docsifyjs/docsify-cli#95]
## Bug Report
Related to docsifyjs/docsify#704 
When following the steps to launch SSR implementation of docsify you get errors and the only example repo doesn't work.

#### Steps to reproduce
`npm i now docsify-cli -D`
copy docsify's package.json info in your empty project package.json
```
{
    "name": "my-project",
    "scripts": {
      "start": "docsify start . -c ssr.config.js",
      "deploy": "now -p"
    },
    "files": [
      "docs"
    ],
    "docsify": {
      "config": {
        "basePath": "https://docsify.js.org/",
        "loadSidebar": true,
        "loadNavbar": true,
        "coverpage": true,
        "name": "docsify"
      }
    }
  }
```
Launch `npm start` or `docsify start . -c ssr.config.js` 

#### What is current behaviour
The error `unknown argument: ssr.config.js` is generated preventing the server to run.

#### What is the expected behaviour
Not sure, haven't found any working sample

#### Other relevant information
By launching the server doing `docsify start .`, the server runs but nothing is rendered.

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Mojave 10.14.5
- Node.js version: 10.16.0
- npm/yarn version: npm 6.13.7
- Browser version: Chrome 75.0.3770.142
- Docsify version: 4.4.0
- Docsify plugins: none

**Comment by anikethsaha** [comment]
cc @jamesgeorge007

**Comment by sy-records** [comment]
@anikethsaha Hello, How should this problem be solved? 
There is also docsifyjs/docsify-ssr-demo#3 .
I tried https://github.com/docsifyjs/docsify-ssr-demo, which can also be re-produce.

**Comment by anikethsaha** [comment]
some issue with argument parsing or something relative. 
Need to take a look in it

**Comment by MichaelCurrin** [comment]
I just ran into this issue.

The part that handles `config` expects `0` arguments instead  of`1` like `port`.

https://github.com/docsifyjs/docsify-cli/blob/afd5379adbe63f4e39b0789f4cc8b872d1086781/lib/cli.js#L97

**Comment by MichaelCurrin** [comment]
I made a local change to `1` and it picked up the config file without the error of unknown argument.

See PR #105.
